### ISSUE TITLE
Unexpected token on css

### ISSUE THREAD

**Issue by panvourtsis** [dmitriykharchenko/react-material-grid#3]
Hi, I am trying to import this library and i am getting the problem of "Unexpected token ILLEGAL" on css which means that webpack and babel cannot read it. What i did that did the trick for now is to remove from Grid.js the require of the css and import those files in my index.js. 

Tried several other things in webpack with no luck. Any suggestions?

**Comment by dmitriykharchenko** [comment]
Hi @panvourtsis! 
Sorry for a late reply, what is your `webpack` config?

**Comment by panvourtsis** [comment]
Hi, its ok, thanks for your reply! My project consists of two webpack configs (the project it is based on the mern starter pack https://github.com/Hashnode/mern-starter). 
See them below.
1st) https://jsfiddle.net/wu94La6a/
2nd) https://jsfiddle.net/kz6wLx4e/
